### ISSUE TITLE
Xamarin.iOS Entitlements

### ISSUE THREAD

**Issue by marlonribeiro01** [HabibAli/FCM-Xamarin-Forms#6]
I've followed your steps to setup FCM on iOS and it's all working well for Debug Mode. But when I build it in release mode and generate .ipa file, it does not install on any iPhone.
Actually it installs until 100% and then just disappears. This is what is shown on Device logs:
Jun 13 17:13:28 iPhone-de-Tatiane atc(Apps)[31] : |com.personaliza.sage-clube-do-contador install failed unrecoverably: Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.6eaBvR/extracted/Payload/SageAppPCLiOS.app : 0xe8008016 (The executable was signed with invalid entitlements.)" UserInfo={LibMISErrorNumber=-402620394, LegacyErrorString=ApplicationVerificationFailed, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.6eaBvR/extracted/Payload/SageAppPCLiOS.app : 0xe8008016 (The executable was signed with invalid entitlements.), SourceFileLine=147}

Do you have any idea about this problem?

**Comment by HabibAli** [comment]
This is related to your code signing 

What you can do is open Xcode and open any sample application and try the same bundle identifier and certificate and try installing it on your iPhone. It will tell you the problem regarding code signing and will also guide how to resolve it

**Comment by marlonribeiro01** [comment]
Oh, I fixed it! I just changed my aps-environment string from "development" to "production". Thanks!
