### ISSUE TITLE
Notifications showing as Alert

### ISSUE THREAD

**Issue by arvindrajachourasiya** [HabibAli/FCM-Xamarin-Forms#9]
Device Tested On: iPhone 5
Version of VS: 2017 MAC
Version of Xamarin: iOS 11

### Actual Behavior
When app is open notifications showing as a ## Alert with Cancel and Ok button. When app is close notifications working properly showing from top.

### Expected Behavior
Notifications should roll out from top as a banner

As we are using alert method

```
private void debugAlert(string title, string message)
		{
			var alert = new UIAlertView(title ?? "Title", message ?? "Message", null, "Cancel", "OK");
			alert.Show();
		}
```

How to show notifications from top when app open. thank you

**Comment by HabibAli** [comment]
this is default behavior of ios. When app is opened, notification never rolls out from top
